name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  run_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Include Workflow from workflow-library
        uses: actions/checkout@v2
        with:
          repository: TomaszZiola/workflow-library
          ref: master
          path: workflow-library/V1/pipelines/main_pipe.yml

      - name: Run Main Pipeline
        run: gh workflow run main_pipe.yml
