name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Include Workflow from workflow-library
        uses: actions/checkout@v2
        with:
          repository: TomaszZiola/workflow-library
          ref: master
          path: workflow-library/V1/pipelines/main_pipe.yml

      - name: Run Main Pipeline
        run: |
          cd workflow-library/V1/pipelines
          bash main_pipe.yml  # Assuming it's a bash script, adjust accordingly
