name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  run_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Gradle check
        run: gradle check
