name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  run_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Include Workflow from workflow-library
        uses: actions/checkout@v2
        with:
          repository: TomaszZiola/workflow-library
          ref: master
          path: .github/workflows

      - name: Run Main Pipeline
        run: |
          cd .github/workflows
          git checkout master
          bash main_pipe.yml
